### PR TITLE
fix typo: Initial of Bottom Post is BP

### PR DESCRIPTION
**Pull request by DF-wu**
I noticed the initial of Bottom Post (置底文) in the Readme.md was a typo.  
So I make a fix for readme file and source code. 
If there is anything I misunderstand  or got wrong, let me know plz.

### CODE REVIEW

**Comment by WayneChang65** [comment]
Hi @DF-wu ,
At first I'd like to thank for your PR. Actually, PB means "posts at the bottom" but I got a typo in the Readme file (skipBPs). You're right, it can be BP (bottom posts) but I don't wanna change the interface of the module because lots of people have used it. To change the interface will make their projects invalid. That's a terrible thing. 
So, I would appreciate it if you could just fix the typo of readme.md and be a contributor for ptt-crawler. Thanks.

**Comment by DF-wu** [comment]
Hi @WayneChang65, 
Thanks for replying. I can understand the potential side-effect of the change. 
For people may review the code and realize the difference between readme.md and code, how about leaving a note in the readme file?
it would be like 
`In the source code. The Bottom Post would be shown as PB due to consistency issue`.

I would fix the readme.md first and wait for your idea. Thank you :)

**Comment by WayneChang65** [comment]
Hi @DF-wu ,
I think there is a misunderstanding.
Your PR modified the example code in readme.md(Line 55). That'll make confuse for consistency between example code and description.
So I hope you can fix the typo of function description in readme.md (Line 97), and then keep it consistent for description and example code. Thanks.

**Comment by DF-wu** [comment]
oops! My Fault.
I modified it. Review please.

**Pull request merged**
